apiVersion: v2
name: manuka
description: A Helm chart for manuka
type: application
version: 0.9.1
appVersion: 2.0.0-13-gc2e57b7
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
- name: shibd
  repository: oci://registry.rc.nectar.org.au/nectar-helm
  version: 1.x.x
