apiVersion: v2
name: manuka
description: A Helm chart for manuka
type: application
version: 3.2.1
appVersion: 3.0.0-24-g340ede8
sources:
- https://github.com/NeCTAR-RC/manuka-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.31.3
- name: shibd
  repository: oci://registry.rc.nectar.org.au/nectar-helm
  version: 1.3.1
- name: mariadb
  version: 21.0.3
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: rabbitmq
  version: 16.0.12
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.rabbitmq
- name: memcached
  version: 7.9.4
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
