apiVersion: v2
name: manuka
description: A Helm chart for manuka
type: application
version: 2.6.0
appVersion: 3.0.0-8-g3aeed8e
sources:
- https://github.com/NeCTAR-RC/manuka-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.20.3
- name: shibd
  repository: oci://registry.rc.nectar.org.au/nectar-helm
  version: 1.3.0
- name: mariadb
  version: 18.2.5
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: rabbitmq
  version: 14.4.4
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.rabbitmq
- name: memcached
  version: 7.4.8
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
