apiVersion: v2
name: manuka
description: A Helm chart for manuka
type: application
version: 2.16.0
appVersion: 3.0.0-9-g8747e7b
sources:
- https://github.com/NeCTAR-RC/manuka-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.20.5
- name: shibd
  repository: oci://registry.rc.nectar.org.au/nectar-helm
  version: 1.3.0
- name: mariadb
  version: 19.0.1
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: rabbitmq
  version: 14.6.3
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.rabbitmq
- name: memcached
  version: 7.4.10
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
