apiVersion: v2
name: manuka
description: A Helm chart for manuka
type: application
version: 3.1.7
appVersion: 3.0.0-18-g9886b05
sources:
- https://github.com/NeCTAR-RC/manuka-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.29.1
- name: shibd
  repository: oci://registry.rc.nectar.org.au/nectar-helm
  version: 1.3.1
- name: mariadb
  version: 20.2.2
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: rabbitmq
  version: 15.3.1
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.rabbitmq
- name: memcached
  version: 7.6.3
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
