apiVersion: v2
name: manuka
description: A Helm chart for manuka
type: application
version: 2.23.7
appVersion: 3.0.0-10-g3b0dfe5
sources:
- https://github.com/NeCTAR-RC/manuka-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.23.0
- name: shibd
  repository: oci://registry.rc.nectar.org.au/nectar-helm
  version: 1.3.0
- name: mariadb
  version: 19.0.7
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: rabbitmq
  version: 15.0.0
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.rabbitmq
- name: memcached
  version: 7.4.15
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
