apiVersion: v2
name: manuka
description: A Helm chart for manuka
type: application
version: 3.1.15
appVersion: 3.0.0-24-g340ede8
sources:
- https://github.com/NeCTAR-RC/manuka-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.30.0
- name: shibd
  repository: oci://registry.rc.nectar.org.au/nectar-helm
  version: 1.3.1
- name: mariadb
  version: 20.4.3
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: rabbitmq
  version: 16.0.1
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.rabbitmq
- name: memcached
  version: 7.8.1
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
