apiVersion: v2
name: manuka
description: A Helm chart for manuka
type: application
version: 3.1.2
appVersion: 3.0.0-15-ge4ffdae
sources:
- https://github.com/NeCTAR-RC/manuka-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.26.0
- name: shibd
  repository: oci://registry.rc.nectar.org.au/nectar-helm
  version: 1.3.1
- name: mariadb
  version: 19.1.2
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: rabbitmq
  version: 15.0.5
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.rabbitmq
- name: memcached
  version: 7.5.2
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
