apiVersion: v2
name: manuka
description: A Helm chart for manuka
type: application
version: 1.0.7
appVersion: 2.0.0-13-gc2e57b7
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
- name: shibd
  repository: oci://registry.rc.nectar.org.au/nectar-helm
  version: 1.x.x
- name: mariadb
  version: 11.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: components.mariadb
- name: rabbitmq
  version: 13.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.rabbitmq
- name: memcached
  version: 7.x.x
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
