apiVersion: v2
name: manuka
description: A Helm chart for manuka
type: application
version: 3.2.2
appVersion: 3.0.0-25-g1e73b3e
sources:
- https://github.com/NeCTAR-RC/manuka-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.31.4
- name: shibd
  repository: oci://registry.rc.nectar.org.au/nectar-helm
  version: 1.3.1
- name: mariadb
  version: 23.0.5
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: rabbitmq
  version: 16.0.14
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.rabbitmq
- name: memcached
  version: 8.0.5
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
