# Default values for manuka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


conf:
  terms_version: v1
  support_url:
  default_target:
  whitelist:
  fake_shib: false
  transport_url:
  notifier:
  database:
    connection:
  smtp:
    from_email:
  keystone:
    auth_url:
    username: manuka
    project_name: service
    memcached_servers: []
  freshdesk:
    domain:
  oslo_messaging_rabbit:
    ssl: true
  orcid:
    sandbox: false

vault:
  role: k8s
  settings_secret: 'path/to/secret/in/vault'

api:
  replicaCount: 1
  pdb:
    enabled: false
    minAvailable: 1
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

worker:
  replicaCount: 1
  pdb:
    enabled: false
    minAvailable: 1
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

image:
  repository: registry.rc.nectar.org.au/nectar/manuka
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


wait_for:
  db:
    host:
    port: 3306

shibd:
  image:
    repository: registry.rc.nectar.org.au/nectar/shibd
    pullPolicy: IfNotPresent
    tag: "2.0.1"
  resources: {}


tuakiri:
  domain_id:
  metadata_url:

apache:
  servername:


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

gateway:
  enabled: false
  annotations: {}
  hostnames:
    - chart-example.local
  parentRefs:
    - name: default

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

components:
  mariadb: false
  rabbitmq: false
  memcached: false
