apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manuka.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
data:
  manuka.conf: |
{{ include "manuka-conf" . | indent 4 }}
  policy.yaml: |
    reader: 'role:reader or role:read_only or role:cloud_admin or role:helpdesk or role:AllocationAdmin or role:AllocationApprover'
    writer: 'role:cloud_admin or role:helpdesk or role:AllocationAdmin or role:AllocationApprover'
    account:user:list: 'rule:admin_required or role:monitoring'
