apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manuka.fullname" . }}-apache-root
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
data:
  wsgi.py: |
    from manuka import app
    application = app.create_app()
  robots.txt: |
    User-agent: *
    Disallow: /
