apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manuka.fullname" . }}-apache
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
data:
  000-default.conf: |
{{ include "apache-conf" . | indent 4 }}
