apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manuka.fullname" . }}-shibd
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
data:
  shibboleth2.xml: |
{{ include "shibboleth2-conf" . | indent 4 }}
