apiVersion: v1
kind: Service
metadata:
  name: {{ include "manuka.fullname" . }}
  labels:
    {{- include "manuka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "manuka.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
